version: '3.7'

services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./demo:/code/demo
    networks:
      - appnet
    depends_on:
      - php
  php:
    build: docker/php
    volumes:
      - .:/code
    networks:
      - appnet

networks:
  appnet:
    driver: bridge